#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    moody-core-web-80-http:
      entrypoints:
        - http-33002
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "moody-core-redirectHttps"
    moody-core-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "moody-core-redirectHttps"
    moody-core-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "moody-core-redirectHttps"
    
    
    
    moody-core-web-80-https:
      entrypoints:
        - http-33003
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-web-80"
      ruleSyntax: v3
      
      tls: true
      
    moody-core-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    moody-core-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^moody-core\.ddev\.site$`)
      
      service: "moody-core-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    moody-core-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    moody-core-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-moody-core-web:80
        
    moody-core-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-moody-core-web:8025
        
    
    
    moody-core-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-moody-core-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/moody-core.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/moody-core.key